### ISSUE TITLE
Updater thread not doing its job

### ISSUE THREAD

**Issue by Tromador** [eyeonus/EDDBlink-listener#14]
When I start the listener from cold it duly checks for new data @ EDDB and correctly runs the plugin.

However, for at least the last couple of days (possibly longer) it has not been doing so. The server still logs
`No update, checking again in 1 hour.` but despite there clearly being an update, nothing is downloaded.

**Comment by eyeonus** [comment]
Best guess at this time is that the value that holds the dump's timestamp
is refusing to be changed.

If so, putting a line to delete that variable address after using it to check
would fix the problem.

**Comment by Tromador** [comment]
eyeonus - I'll see if I can work it out myself, don't worry unless you want to, or I need to bug you about it. 

I'll just run with this for a bit and see what the times are doing and work back from there.

```
            print("No update, checking again in "+ next_check + ".")
            print("Localmodded: " + gmtime(localModded) + ". Dumpmodded: " + gmtime(dumpModded) + ".")
```

**Comment by Tromador** [comment]
Oh wait... `strftime("%Y-%m-%d %H:%M:%S", gmtime(localModded))`

**Comment by Tromador** [comment]
Aaand... 
```
No update, checking again in 1 hour.
Localmodded: 2018-07-25 08:50:17. Dumpmodded: 2018-07-25 08:36:26.
```

Those times look correct, so I'll see what happens in the morning.

**Comment by Tromador** [comment]
Perversely it worked find this morning and I've yet to update to the latest. (which I shall do now).

```
Localmodded: 2018-07-25 08:50:17. Dumpmodded: 2018-07-25 08:36:26.
Localmodded: 2018-07-26 09:12:59. Dumpmodded: 2018-07-26 08:45:09.
```

I'll monitor for the next 48 hours or so and if it updates correctly, I'll close this ticket.

**Comment by Tromador** [comment]
This has been fine for the past couple of days. Closing.
