### ISSUE TITLE
Linux shebang

### ISSUE THREAD

**Issue by Tromador** [eyeonus/EDDBlink-listener#2]
Can you put a 

#!/usr/bin/env python

at the top so I can run it direct from command line. Obviously I can do this myself, but if you do it once in master I don't need to do it every time I download.

(ideally #!/usr/bin/env python3.6 for me)

**Comment by eyeonus** [comment]
Sure. Totally useless on Windows, which is why I didn't think of it. I don't currently have a *nix box.

**Comment by eyeonus** [comment]
And the forums are down so we can't even use the pm system right now. >(
