### ISSUE TITLE
(question) What to do with "Not found in Stations"

### ISSUE THREAD

**Issue by Karmak23** [eyeonus/EDDBlink-listener#22]
Hi,

(not a real bug, sorry, I didn't find any TD/EDDBlink channel on the EDCD discord, so I'm here)

I started the database with TD `-P EDDBlink -O all`. Then, I start the listener, but I get this kind of messages all along the listener's run (one thenth, roughly, sometimes more, sometimes less) :
```
ERROR: Not found in Stations: WREDGUIA HH-D D12-55/T6Z-L0Z
[…]
ERROR: Not found in Stations: 70 VIRGINIS/V1H-T3G
```
How should I consider them ? Is there a way to add these stations to get the prices update ?

**Comment by eyeonus** [comment]
Those are obviously Fleet Carriers, you can tell from the station names.

The error you're talking about comes from here:
https://github.com/eyeonus/EDDBlink-listener/blob/18206da4d7cf41c2d05875676d65e7325ada8862/eddblink_listener.py#L619-L645

It means that station isn't in the Stations table of the database:
https://github.com/eyeonus/EDDBlink-listener/blob/18206da4d7cf41c2d05875676d65e7325ada8862/eddblink_listener.py#L894-L908

The Stations table is created/updated using the 'stations.jsonl' file from EDDB.io, which is updated once every ~24 hours, using the eddblink plugin in TD proper:
https://github.com/eyeonus/Trade-Dangerous/blob/7b8fc7ebb92f70b0e18b7b163785e0ef17addc7b/tradedangerous/plugins/eddblink_plug.py#L34

https://github.com/eyeonus/Trade-Dangerous/blob/7b8fc7ebb92f70b0e18b7b163785e0ef17addc7b/tradedangerous/plugins/eddblink_plug.py#L466-L635


So, there are two solutions:
1) Wait for the station to be added to EDDB.io, which should occur in not more than 24 hours.

2) Alter the code to handle the case where the station isn't found in the database (https://github.com/eyeonus/EDDBlink-listener/blob/18206da4d7cf41c2d05875676d65e7325ada8862/eddblink_listener.py#L642-L645) to first check that the system it's in does exist in the database, insert the system into the database if not (with the correct information), and then insert the station into the database.

If the system already exists in the database, that's not much of a problem. If the database is updated using the 'systemfull' option in TD's eddblink plugin, then **all** the systems *should* be in the database.

If the system is not already in the database (such as the case when doing a normal system import, which only imports systems that are populated), we need to know the system's id, name, and x, y, & z position on the galactic map, which IIRC is not included in the EDDN message, making the task a bit hard.

In either case, once the system is verified to exist in the database, the station can then be inserted in the same way as it is done in eddblink:
https://github.com/eyeonus/Trade-Dangerous/blob/7b8fc7ebb92f70b0e18b7b163785e0ef17addc7b/tradedangerous/plugins/eddblink_plug.py#L548-L557

It's also probably a good idea to update the csv files after doing this, which is done with the 'exportTableToFile()" method in TD's CSV Exporter module, and then to call the listener's update_dicts() method.

https://github.com/eyeonus/Trade-Dangerous/blob/7b8fc7ebb92f70b0e18b7b163785e0ef17addc7b/tradedangerous/csvexport.py#L102

**Comment by eyeonus** [comment]
Due to amount of work involved in option 2, I think you can understand why I went with option 1. ;)

If you feel the need to implement option 2 yourself, feel free to do so, and also don't hesitate to issue a pull request once you have it working, and I'll merge it in.

**Comment by eyeonus** [comment]
Oh yes, and the 'systemfull' option isn't covered by 'all' in the eddblink plugin, it has to be explicitly passed. This is because the database of ALL systems that you would get with 'systemfull' is astronomically huge, as in larger than the entire database of everything else combined huge, so it isn't run by default.

**Comment by Karmak23** [comment]
OK. thanks for this complete explanation. I'm quite new to the game thus not yet comfortable with FCs.

I didn't find any CLI flag such as `--avoid-fc` in the doc to make TD not send me on them (i was stuck with no permissions in the middle of a `run`). 

I didn't look at the code yet, how difficult could it be to port TD & the listener to PGSQL ? traditonally this is just a matter of changing the database link/source. If it's the case with TD I would like to switch DB to avoid "database is locked" errors (which I get a lot, with some deadlocks sometimes which force me to force shutdown the listener.

I'd like to make some tests with pgSQL, to (in the longer term) integrate TD in some kind of "route finder / helper" installed on our home server and that we could share as a wing, for me and my son (12 years old), which finds the game a little complicated (and it is, for a child…) but persists in playing it because, it is… well… beautiful, interesting, marvelously complex…

**Comment by Karmak23** [comment]
perhaps a `--no-fc` like `--no-planet` ?

**Comment by Tromador** [comment]
The database schema is located at https://github.com/eyeonus/Trade-Dangerous/blob/master/tradedangerous/templates/TradeDangerous.sql

My experience is that no two implementations of SQL are quite the same and so to support PGSQL I would imagine that you will need to write a schema which provides similar functionality and then go through the whole of the code checking the SQL statements, tweaking as necessary with appropriate IFDEF logic to cope with multiple database options.

Unfortunately it's a huge pile of work, which is a shame as SQLite hasn't really scaled well with the growth of the dataset.

If you wanted to do that work, it would be fantastic and I would be very happy to run server on the more robust PGSQL backend.

It's not, however as simple as including the relevant postgres modules and making a different database connection.

**Comment by eyeonus** [comment]
> perhaps a `--no-fc` like `--no-planet` ?

Already done:
https://github.com/eyeonus/Trade-Dangerous/commit/339b2af4e58ef9296a84548605359517511425be

The argument is '--fleet-carrier' ( or '--fc') and functions like the '--planetary' option: it takes any of [YN?].

**Comment by eyeonus** [comment]
Switching to a different SQL implementation would be awesome, but I barely understand the one TD uses and would be hard pressed to do that myself without a LOT of research, which is why I haven't done it.

**Comment by Karmak23** [comment]
> Switching to a different SQL implementation would be awesome, but I barely understand the one TD uses and would be hard pressed to do that myself without a LOT of research, which is why I haven't done it.

OK. I can't promise anything, I'm on ED (game + tools) only on my freetime. But I'm confortable with ORMs and DB schemata. 

The PG build would help a lot on "robustness" and huge setups (all systems would not be a problem, besides the size). 

Anyway, if I look at it, il will probably try to avoid ifdefs as much as possible, and go for an ORM which would handle that dirty work. Switch to a database connector/engine (perhaps SQLalchemy, perhaps not ; I liked a lot the Django ORM, but it was 10 years ago from now… Don't know what it became and not sure it would be relevant ; i need to dive in the code to make an answer). This will be a big work. Still don't know if it's a prerequisite of the helper I want to code, or if i could code it afterwards. For now I run the eddblink on my home server ; perhaps I will run it on my datacenter one, I'm still testing, digging. I will hang on EDCD discord if I start something.

Marvelous for the `--no-fc` ! Perhaps it should be the default as newcomers could be brought to FCs while they don't have permission to dock. Hopefully when I got to it I had fuel to get back to a near station. Else it would have been harder ;-)

Thanks for all your answers ! Best regards & fly safe :-)

**Comment by eyeonus** [comment]
No worries. See you in the black. o7
