### ISSUE TITLE
listings-live grows larger than listings

### ISSUE THREAD

**Issue by Tromador** [eyeonus/EDDBlink-listener#6]
Redownloaded latest eyeTD & listener, deleted all old files and ran from clean to be 100% sure.

Still ends up with filesizes as e.g.

-rw-rw-r--. 1 elite elite 156303047 Jun 28 08:02 listings.csv
-rw-rw-r--. 1 elite elite 158952566 Jun 28 18:38 listings-live.csv

**Comment by eyeonus** [comment]
I updated the plugin, this issue shouldn't happen anymore.

Bad thing is that it won't remember which entries are from the dump and which are from the live file after a clean run. I'll have to figure out something else for that.

**Comment by Tromador** [comment]
Okay - downloaded latest eyetd & listener to server & run clean.

Unless something wierd happens with the server, it shouldn't be a major issue in any case. Make it a low priority, unless you get a sudden brainwave.

**Comment by eyeonus** [comment]
Should be working correctly after this update to TD:

https://github.com/eyeonus/Trade-Dangerous/commit/9639fdb777ae996e4ef2bbdcbc6ab9b9af254bdd

This includes remembering which listings are from the listings file and which are from the live file, which we had a problem with before.
